#:schema node_modules/wrangler/config-schema.json
name = "ctm-app"
compatibility_date = "2024-04-03"
pages_build_output_dir = "dist"

[vars]
# Add your environment variables here if needed
# VITE_NEON_DATABASE_URL = "your-database-url"
